config/routes.rb
Rails.application.routes.draw do
  root 'session#login'
  get 'sequence/input'
  get 'sequence/view'
  get 'session/login'
  post 'session/create'
  get 'session/logout'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

# Модель пользователя
class User < ApplicationRecord
  has_secure_password validations: false

  validate :password_presence
  validates :password, confirmation: { message: 'Пароли не совпадают' }

  validates :username, length: { minimum: 3, message: 'не может быть короче 3-х символов' },
                       uniqueness: { message: 'уже занято' }

  validates :email, allow_blank: true,
                    uniqueness: { message: 'занята другим пользователем' },
                    format: { with: /\A[^@;"\s]+@[^@;"\s]+\.[^@;"\s]+\z/, message: 'не может быть использована' }

  def password_presence
    errors.add(:password, 'не может быть пустым') unless password_digest.present?
  end

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper

  before_action :require_login

  private

  def require_login
    unless signed_in?
      flash[:danger] = 'Требуется логин'
      redirect_to session_login_url
    end
  end
end

app/controllers/sequence_controller.rb
# frozen_string_literal: true

# Контроллер для последовательности
class SequenceController < ApplicationController
  def input
  end

  def view
    @input = validate_input params[:values]
    subs_arr = find_increasing_subs.filter { |arr| arr.count > 1 }
    @subs = subs_arr.map { |subseq| subseq.join(' ') }
    @result = subs_arr.max_by(&:length).join(' ')
    @input = @input.join(' ')
  rescue StandardError => e
    @error = case e.class.to_s
             when 'ArgumentError' then 'Введены посторонние символы'
             when 'NoMethodError' then 'Последовательность не найдена'
             else e
             end
  end

  private

  def find_increasing_subs
    @input.each_with_object([[]]) do |el, acc|
      acc << [] if acc[-1].any? && el <= acc[-1][-1]
      acc[-1] << el
    end
  end

  def validate_input(input)
    raise 'Ошибочный GET-запрос' if input.nil?
    raise 'Вы ничего не ввели' if input.empty?

    result = input.split.map { |el| Integer el }
    raise 'Последовательность короче 10 чисел' if result.length < 10

    result
  end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]

  def login
    redirect_to sequence_input_path if signed_in?
  end

  def create
    user = User.find_by(username: params[:login])

    if user&.authenticate(params[:password])
      sign_in user
      redirect_to root_path
    else
      flash[:danger] = user.nil? ? 'Пользователь с таким именем не существует' : 'Неверный пароль'
      redirect_to session_login_path
    end
  end

  def logout
    sign_out
    redirect_to session_login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[new create]

  # GET /users or /users.json
  def index
    if current_user.admin?
      @users = User.all
    else
      redirect_to '/403'
    end
  end

  # GET /users/1 or /users/1.json
  def show
    redirect_to '/403' unless current_user.id == @user.id || current_user.admin?
  end

  # GET /users/new
  def new
    redirect_to current_user if current_user

    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to '/403' unless current_user.id == @user.id || current_user.admin?
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html do
          flash[:success] = 'Пользователь успешно создан'
          redirect_to @user
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if current_user.id == @user.id || current_user.admin?
      respond_to do |format|
        if @user.update(user_params)
          format.html do
            flash[:success] = 'Параметры пользователя успешно обновлены'
            redirect_to @user
          end
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :forbidden }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if current_user.id == @user.id || current_user.admin?
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :forbidden }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      if current_user == @user || current_user.nil?
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
      elsif current_user.admin?
        params.require(:user).permit(:username, :email, :admin)
      end

      # if current_user.nil? || !current_user.admin?
      #   params.require(:user).permit(:username, :email, :password, :password_confirmation)
      # else
      #   params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin)
      # end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sequence_helper.rb
module SequenceHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 2.days }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar', user: current_user %>
    <main class="container mt-3">
      <%= render 'shared/flash' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/sequence/input.html.erb
<h1 class="m-3">Поиск последовательности</h1>
<p class="m-3 text-truncate">Будет определена наиболее длинная монотонно возрастающая последовательность чисел.</p>
<div class="w-50">
    <%= form_tag sequence_view_path, method: 'get', class: 'm-3' do %>
            <div class="col-12"><%= label_tag :values, 'Введите последовательность чисел через пробел:' %></div>
            <div class="row mt-2">
                <div class="col-11 p-1 m-0"><%= text_field_tag :values, '', class: 'form-control', required: true %></div>
                <div class="col-1 p-1 m-0"><%= button_tag "Найти", type: 'submit', name: nil, class: 'btn btn-primary' %></div>
            </div>
    <% end %>
</div>

app/views/sequence/view.html.erb
<% if @error %>
    <% flash.now[:danger] = @error %>
    <p class="m-3">Результатов поиска нет<p>
<% else %>

<h1 class="m-3">Результат поиска</h1>

<div class="m-3">Вы ввели: <%= @input %></div>
<div class="w-25 m-3 table-responsive">
    <table class="table table-striped table-sm table-bordered">
        <thead class="text-center">
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Последовательность</th>
            </tr>
        </thead>
        <tbody>
            <% @subs.each.with_index(1) do |subseq, ind| %>
                <tr>
                    <th scope="row" class="col-1 text-center"><%= ind %></th>
                    <td><%= subseq %></td>
                </tr>
            <% end %>
            <tr>
                    <th scope="row" class="col-1 text-center">Ответ</th>
                    <td><%= @result %></td>
                </tr>
        <tbody>
    </table>
</div>
<% end %>
<br>
<button type="button" class="btn btn-link">
    <%= link_to 'Домой', root_path %>
</button>

app/views/session/login.html.erb
<%= form_with url: session_create_url, method: :post, local: true do |form| %>
  <div class="field mb-3">
    <%= form.label :login, 'Логин' %>
    <%= form.text_field :login, required: true, label: 'Логин', class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :password, 'Пароль' %>
    <%= form.password_field :password, required: true, label: 'Пароль', class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.submit 'Войти', class: 'btn btn-primary' %>
  </div>
<% end %>
<%= link_to 'Зарегистрироваться', new_user_path %>

app/views/shared/_flash.html.erb
<ul class="p-0">
    <% flash.each do |key, val| %>
        <%= tag.div val, class: "alert alert-#{key} mt-4", role: "alert" %>
    <% end %>
</ul>

app/views/shared/_navbar.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="p-4" style="background-color: #a0c0ff;">
    <h5 class="text-white h4">Управление</h5>
      <ul style="list-style-type: none;">
        <li><div class="w-25"><a class="nav-link" href="<%= users_path %>">Список пользователей</a></div></li>
      </ul>
  </div>
</div>
<nav class="navbar navbar-light" style="background-color: #80a0ff;">
  <div class="container-fluid">
    <% if user&.admin? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <% end %>

    <% if user %>
      <span class="nav-item">
            <a class="nav-link" href="<%= sequence_input_path %>">Посчитать</a>
      </span>
      <span class="nav-item dropdown ms-auto dropstart">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= user&.username %>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="<%= user_url(current_user) %>">Профиль</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="<%= session_logout_path %>">Выйти</a></li>
        </ul>
      </span>
    <% else %>
      <span class="nav-item ms-auto">
          <a class="nav-link" href="<%= session_login_path %>">Войти</a>
      </span>
    <% end %>
  </div>
  
</nav>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <% unless current_user.nil? || current_user == user %>
    <p class="text-danger">Вы редактируете учетную запись другого пользователя!</p>
  <% end %>

  <% if user.errors.any? %>
    <% user.errors.each do |error| %>
      <% col_name = case error.attribute %>
                    <% when :username then 'Имя пользователя' %>
                    <% when :password then 'Пароль' %>
                    <% when :email then 'Электронная почта' %>
                    <% else %>
                    <% '' %>
                    <% end %>
      <% flash.now[:danger] = "#{col_name} #{error.message}" %>
    <% end %>
  <% end %>
  <div class="w-50 m-3 table-responsive">
    <table class="table table-borderless">
      <tr>
        <th scope="row" class="col-4 text-center"><%= form.label :username, 'Имя пользователя' %></th>
        <td scope="row" class="col-8 text-center"><%= form.text_field :username, style: 'min-width: 100%' %></td>
      </tr>

      <tr>
        <th scope="row" class="col-4 text-center"><%= form.label :email %></th>
        <td scope="row" class="col-8 text-center"><%= form.text_field :email, style: 'min-width: 100%' %></td>
      </tr>

      <% if current_user&.admin? %>
        <tr>
          <th scope="row" class="col-4 text-center"><%= form.label 'Статус' %></th>
          <td scope="row" class="col-8 text-center">
            <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
              <%= form.radio_button :admin, 'true', class: "btn-check"%>
              <%= form.label 'Администратор', class: "btn btn-outline-primary", for: :user_admin_true%>
              <%= form.radio_button :admin, 'false', class: "btn-check"%>
              <%= form.label 'Пользователь', class: "btn btn-outline-primary", for: :user_admin_false %>
            </div>
          </td>
        </tr>
      <% end %>

      <% if current_user.nil? || current_user == user %>
        <tr>
          <th scope="row" class="col-4 text-center"><%= form.label :password, 'Пароль' %></th>
          <td scope="row" class="col-8 text-center"><%= form.password_field :password, style: 'min-width: 100%' %></td>
        </tr>

        <tr>
          <th scope="row" class="col-4 text-center"><%= form.label :password_confirmation, 'Подтверждение пароля' %></th>
          <td scope="row" class="col-8 text-center"><%= form.password_field :password_confirmation, style: 'min-width: 100%' %></td>
        </tr>
      <% end %>
      <tr>
        <td scope="row" colspan="2" align="right">
          <button type="submit" class="btn btn-primary">
            Сохранить
          </button>
        </td>
      </tr>
    </table>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Редактирование пользователя</h1>

<%= render 'form', user: @user %>

<%= link_to 'Посмотреть профиль', @user %> |
<%= link_to 'На главную', root_path %>

app/views/users/index.html.erb
<h1>Пользователи</h1>

<div class="w-75 m-3 table-responsive">
  <table class="table table-sm table-borderless">
    <thead>
      <thead class="text-center">
        <th>Имя пользователя</th>
        <th>Email</th>
        <th>Администратор</th>
        <th colspan="3"></th>
      </thead>
    </thead>

    <tbody class="text-start">
      <% @users.each do |user| %>
        <tr>
          <td class="col-3"><%= user.username %></td>
          <td class="col-3"><%= user.email %></td>
          <td class="col-2 text-center"><%= user.admin? ? 'Да' : 'Нет' %></td>
          <td class="col-1"><%= link_to 'Профиль', user %></td>
          <td class="col-1"><%= link_to 'Изменить', edit_user_path(user) %></td>
          <td class="col-1"><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>Зарегистрироваться</h1>

<%= render 'form', user: @user %>
<%= link_to 'Войти', session_login_path %>

app/views/users/show.html.erb
<p>
  <strong>Имя пользователя:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Статус:</strong>
  <%= @user.admin? ? 'Администратор' : 'Пользователь' %>
</p>

<%= link_to 'Редактировать', edit_user_path(@user) %>